<a href="https://colab.research.google.com/github/YaXun112/Colab/blob/DL/HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
import os

Dataset_File = "HealthCheck.csv"
if not os.path.isfile(Dataset_File):
  os.system("wget https://raw.githubusercontent.com/cnchi/datasets/master/" + Dataset_File)

In [3]:
dfCSV = pd.read_csv("HealthCheck.csv")
print(dfCSV)

      Race  Height_cm  Weight_kg Over70yr
0    White      186.0       90.0      Yes
1  African      185.0       98.0       No
2    Asian      175.0       80.0       No
3  African      170.0       75.0      Yes
4    Asian      164.0        NaN       No
5    Asian      170.0       72.0      Yes
6    White      178.0       75.0       No
7    White        NaN       89.0      Yes
8  African      165.0       79.0      Yes


In [4]:
X = dfCSV.iloc[:, :-1].values
Y = dfCSV.iloc[:, 3].values

In [5]:
print(X)

[['White' 186.0 90.0]
 ['African' 185.0 98.0]
 ['Asian' 175.0 80.0]
 ['African' 170.0 75.0]
 ['Asian' 164.0 nan]
 ['Asian' 170.0 72.0]
 ['White' 178.0 75.0]
 ['White' nan 89.0]
 ['African' 165.0 79.0]]


In [6]:
print(Y)

['Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes']


In [7]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [8]:
print(X)

[['White' 186.0 90.0]
 ['African' 185.0 98.0]
 ['Asian' 175.0 80.0]
 ['African' 170.0 75.0]
 ['Asian' 164.0 82.25]
 ['Asian' 170.0 72.0]
 ['White' 178.0 75.0]
 ['White' 174.125 89.0]
 ['African' 165.0 79.0]]


In [9]:
LabelEncoder = LabelEncoder()

Y = LabelEncoder.fit_transform(Y).astype('float64')

In [10]:
print(Y)

[1. 0. 0. 1. 0. 1. 0. 1. 1.]


In [11]:
ary_dummies = OneHotEncoder().fit_transform(X[:, 0].reshape(-1, 1)).toarray()
X = np.delete(X, 0, 1)
X = np.concatenate((ary_dummies, X), axis=1)

In [12]:
print(ary_dummies)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [13]:
print(X)

[[0.0 0.0 1.0 186.0 90.0]
 [1.0 0.0 0.0 185.0 98.0]
 [0.0 1.0 0.0 175.0 80.0]
 [1.0 0.0 0.0 170.0 75.0]
 [0.0 1.0 0.0 164.0 82.25]
 [0.0 1.0 0.0 170.0 72.0]
 [0.0 0.0 1.0 178.0 75.0]
 [0.0 0.0 1.0 174.125 89.0]
 [1.0 0.0 0.0 165.0 79.0]]


In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [15]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [16]:
print('自變數訓練集：\n',X_train,'\n')
print('應變數訓練集：\n',Y_train,'\n')
print('自變數測試集：\n',X_test,'\n')
print('應變數測試集：\n',Y_test,'\n')

自變數訓練集：
 [[ 1.15470054 -0.63245553 -0.63245553  1.30941777  1.89111602]
 [-0.8660254   1.58113883 -0.63245553 -1.19037979  0.07416141]
 [ 1.15470054 -0.63245553 -0.63245553 -1.07134181 -0.30076573]
 [-0.8660254  -0.63245553  1.58113883  0.47615192 -0.76221452]
 [ 1.15470054 -0.63245553 -0.63245553 -0.47615192 -0.76221452]
 [-0.8660254  -0.63245553  1.58113883  1.42845575  0.96821844]
 [-0.8660254   1.58113883 -0.63245553 -0.47615192 -1.10830111]] 

應變數訓練集：
 [0. 0. 1. 0. 1. 1. 1.] 

自變數測試集：
 [[-0.8660254  -0.63245553  1.58113883  0.01487975  0.85285625]
 [-0.8660254   1.58113883 -0.63245553  0.11903798 -0.18540353]] 

應變數測試集：
 [1. 0.] 

